sudo: false
language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
install: make travis-install
script: make travis-script
after_success:
  - coveralls
  - codeclimate-test-reporter
deploy:
  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: "Andrew.Hawker"
    password:
      secure: kKVY6Z6cnQRPjexKM7V5ljfsFqp5ASxHcvypypBKWoqSVQAuWrUsjbxjhcLpQ8QHXLXJR+6FCat2igseT6mpjdmnqcavR417Em0OE2TPe63rwsPhvbwMWdKBiPZuRSSLpCKh54L0jqo+BF6VB6oRYaHurjQHI80yELLIzieoAxA1kJZ33pwxVKCmy3VYsi3JF7I0oesmptHkSKa0C5flq759tGRdiNlBKKHFoAxX8dkI2MwVfowYgriYpheN6aNPR1aNrUc8ata9rN82zYuWWThntMXf0BXY7+SdI/01XJCSzO+5H8Hxuh/ctr95j+aZRDuLrxYvhxegURsxn4QTTfx8mTg8D63eN97yTDgMH9sle+IPG6cWLggeVdlysAkQjn6s54tWg4soS3UMJfCsFgomdyEYKey5ohFjRX002XCokqQz2+s+9D1ksG7A3TsK5n5qXYa0/UQ3YbsqJMtmhgHGLQv+aN+ieqHpJo4ThFDNRt473s3RTYtH2CCsAn3nvbEZ5nPXL4VTwExlx3uSmujD1u7UVxaaa0Lzti337PBnKUfAQam+q2oE55iIdRGuL4QaRoafBoYZaZTkpC+P91Zrd7zk2AuLu2Vwk5qUUQImFD7b3+YAroceqGWA+oOIFjFBTCvHN2uI7vIXpwVx3ZJXHmIiG6XgmkUbk3RpXzk=
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "3.4"
  - provider: pypi
    server: https://pypi.python.org/pypi
    user: "Andrew.Hawker"
    password:
      secure: B86Xw3dRV6cBnrB1ehe2R6RNPdTItnIISbIuewFMtW/HzCgWOJ501Jl5a7pgHi7A79nxZlirf7R5W+aR2C+puPDTx5g1ejOnj8qRMZxHjfYCYA8PAvmLJYfj/y4F5sNIFALC1FZytxFL4IikP63dHg7TL8pW0WAcTUwnEkOv2L2WNYMVmSobUA6opAMrQCiz1I0IY39bDYSctiqaRYEAdh9XDnzEhtP1WQdDEDJ5sEfWl8Durka/9296QT3NuSofYXobAgFcQPSWKwdSr58Q0IpEn40fQI+7wAujfnlVYs838m66DS7FLU1c3rxeZ8N/If8js6fEoLwdEG6ANFGgkdMAZF4FLswivd76dg1Q4GurvIyOj0A3Ml7pUANRXu3tD3KA3evoL1K5CxZhghNQycm0x+5ME1M3CMOLSaWyfUYT3Y2O6K/z2jYCg+tlLGGo4cFuZb0OXK69Rs952cWzv0Na8tYeZEQ1++voEv0fG8yQ+bRI1upNPq1tRjzSXG7ifhH9ArA1gb2SBt6eROcKM+c2QWcHcR4I3tlHOYEry7eHktZQTOZffL3JJtKGqaCv3un+c/rUl9edXKxnFD7LM/VM9kWFRNNKaoGWQZYfcSN86HLiX347+CJiHwe9zw6XA/SUrOms1Zesr1B7OmWAywlbU06Off/N5sXfdKTETAw=
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.5"
notifications:
  slack:
    secure: er7+/5OYO3Gwxft7YDn/3m2+VDeC4dmUKR7PcB2KjfQ7DeFMxvmnX+4aHsgD2FkEHYjW9QnBtZbaMptuLPrfeGTk5d/yxWu9NTONiH9AGMSh5NR2fXUKGuHma9j25RG399ZdAlvC46r2JG7flrAaz38SroCa/DxVmG8Tu6vw9eEND50vm9XfGtvDIOC4Nq5JVS+FBbFI4Wkln3fcktnbD/tDt5MHI9q9AuD4QjvtXaQsMBUSptZgtsqlOE/cPnfiv/0rsbcLkm4b+DAQG4qqhL16pzJTbxmXVnxHY+tWu8DUzZer4ufyxPBP43gutWmamaYzUcjSkZ5ZCmX3CGHEDm9oo+1mA9cMFHKeaOnEjCieZvkklR6ycLjgg5c6cdDmNEG4PGELb5XYJmuwcIg2XqpA7H1Ox3Tn/f4hIyHVL8+5uRKHahvDdom5sXjQNcQmd/79YkSZB/s2efhIVDkFlqemgGsDzW4IDOiKRxT6H6bs/q7JFRGsh/nk4lc+iL/w5OjF499/Nx99SAphwdGUH8FL2I0dX7VZZ2awqrkU7hN6wyPH5gg+2/u3fC4/PTI5S1J4xhwz4Q0xwZxaJ9IiGyHF3c50lk+qXfFEXbB1xlu9WKeIhcBZpJvcv5hriC+tnM2kDi0s8+fOe+AL0s6K0dyqg65AVYuUpbCpKgyo3dk=
